### ISSUE TITLE
Error message when Submitting more than one solution

### ISSUE THREAD

**Issue by jasonq13** [Shmoopi/DNBHL#1]
I get this message when trying multiple guesses:

./ShadowPuzzle.sh: line 43: [: 311220153117232: binary operator expected

This is due to the line:
if [ -z "$@" ]; then

It can be fixed by changing it to:

if [ $# -le 0 ]; then

**Comment by Shmoopi** [comment]
Thanks for submitting!  I've updated the script to include your fix.  Let me know if you come across anything else.

**Comment by jasonq13** [comment]
Looks good!
